### ISSUE TITLE
See pages site for the public side of thinsg.

### ISSUE THREAD

**Issue by rdd13r** [Gervi-Hera-Vitr/google-ai-labs#8]
Dada -r uh
Make us a Jekyll blog?

**Comment by rdd13r** [comment]
Okay...

**Comment by rdd13r** [comment]
# Docker based build by Jekyll actions suggestion

```yaml
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"

  clone-and-install:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      options: --user ${{ needs.configure.outputs.uid_gid }}
    steps:
      - uses: actions/checkout@v2
```
